version: '3'
services:
  math-extension:
    image: kwildb/extension-math:multi-arch
    ports:
      - 50055:50051
    restart: on-failure

  kwil:
    image: kwildb/kwil:latest
    ports:
      - 50051:50051
      - 8080:8080
    env_file:
      - ./config/kwil.env
    environment:
      - KWILD_EXTENSION_ENDPOINTS=math-extension:50051
    depends_on:
      - math-extension
    restart: on-failure